# Generated by Django 5.2.7 on 2025-10-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalIDInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('birth_order_number', models.IntegerField()),
                ('birth_governorate', models.CharField(max_length=100)),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
