# Generated by Django 5.2.7 on 2025-10-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('national_id_info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NationalIDInfo',
        ),
    ]
