# Generated by Django 5.2.7 on 2025-10-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('national_id_info', '0002_delete_nationalidinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('execution_time', models.FloatField(help_text='Request duration in seconds')),
                ('status_code', models.IntegerField()),
            ],
        ),
    ]
