# Generated by Django 5.2.7 on 2025-10-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_id_info', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesslog',
            name='execution_time',
            field=models.FloatField(blank=True, help_text='Request duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='apiaccesslog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiaccesslog',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apiaccesslog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiaccesslog',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
