# Generated by Django 5.2.7 on 2025-10-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_id_info', '0004_alter_apiaccesslog_execution_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiaccesslog',
            name='national_id',
        ),
        migrations.AddField(
            model_name='apiaccesslog',
            name='request_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
