# Generated by Django 5.2.7 on 2025-10-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_id_info', '0005_remove_apiaccesslog_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesslog',
            name='request_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
